//
//protobuf关键点:(向前向后兼容)
//1. 永远不要更改字段的标签
//2. 只有当新旧数据相互兼容时,才能更改字段的数据类型, 例如, 可以在int32, uint32, int64, uint64和bool之间进行转换
//3. 永远不要重命名字段
//
//对于grpc服务, 除了不能对协议缓冲区消息执行的操作外
//1. 在不中断现有客户端的情况下, 无法重命名**服务**, 除非可以完全保证客户端和服务器应用程序将被同时更改
//2. 不能重命名**函数**. 引入新函数, 将使用该函数的所有应用程序切换到新函数, 然后删除旧函数

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: protobuf/proto/gm.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// message关键字: 可以理解为go语言中的结构体
type GMRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command  string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args     string `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	PlayerID string `protobuf:"bytes,3,opt,name=playerID,proto3" json:"playerID,omitempty"`
}

func (x *GMRequest) Reset() {
	*x = GMRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_gm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMRequest) ProtoMessage() {}

func (x *GMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_gm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMRequest.ProtoReflect.Descriptor instead.
func (*GMRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_gm_proto_rawDescGZIP(), []int{0}
}

func (x *GMRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *GMRequest) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *GMRequest) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

// 嵌套消息
type GMResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GMResponse) Reset() {
	*x = GMResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_gm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMResponse) ProtoMessage() {}

func (x *GMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_gm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMResponse.ProtoReflect.Descriptor instead.
func (*GMResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_gm_proto_rawDescGZIP(), []int{1}
}

func (x *GMResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GMResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_protobuf_proto_gm_proto protoreflect.FileDescriptor

var file_protobuf_proto_gm_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x67, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x55, 0x0a, 0x09, 0x47, 0x4d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x61, 0x72, 0x67, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44,
	0x22, 0x32, 0x0a, 0x0a, 0x47, 0x4d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x32, 0x32, 0x0a, 0x09, 0x47, 0x4d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x25, 0x0a, 0x08, 0x45, 0x78, 0x63, 0x75, 0x74, 0x65, 0x47, 0x4d, 0x12, 0x0a, 0x2e,
	0x47, 0x4d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x47, 0x4d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_proto_gm_proto_rawDescOnce sync.Once
	file_protobuf_proto_gm_proto_rawDescData = file_protobuf_proto_gm_proto_rawDesc
)

func file_protobuf_proto_gm_proto_rawDescGZIP() []byte {
	file_protobuf_proto_gm_proto_rawDescOnce.Do(func() {
		file_protobuf_proto_gm_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_proto_gm_proto_rawDescData)
	})
	return file_protobuf_proto_gm_proto_rawDescData
}

var file_protobuf_proto_gm_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_proto_gm_proto_goTypes = []interface{}{
	(*GMRequest)(nil),  // 0: GMRequest
	(*GMResponse)(nil), // 1: GMResponse
}
var file_protobuf_proto_gm_proto_depIdxs = []int32{
	0, // 0: GMService.ExcuteGM:input_type -> GMRequest
	1, // 1: GMService.ExcuteGM:output_type -> GMResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_proto_gm_proto_init() }
func file_protobuf_proto_gm_proto_init() {
	if File_protobuf_proto_gm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_proto_gm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GMRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_gm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GMResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_proto_gm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_proto_gm_proto_goTypes,
		DependencyIndexes: file_protobuf_proto_gm_proto_depIdxs,
		MessageInfos:      file_protobuf_proto_gm_proto_msgTypes,
	}.Build()
	File_protobuf_proto_gm_proto = out.File
	file_protobuf_proto_gm_proto_rawDesc = nil
	file_protobuf_proto_gm_proto_goTypes = nil
	file_protobuf_proto_gm_proto_depIdxs = nil
}
